[project]
name = "llama-3-elyza-jp-8b-ft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.10"
dependencies = [
    "datasets>=3.2.0",
    "peft>=0.14.0",
    "pynvml>=12.0.0",
]
